### ISSUE TITLE
vm discovery

### ISSUE THREAD

**Issue by kcwhite1** [dav3860/vmbix#27] opened 2016-05-24 23:18 UTC
Hi, I was wondering if it would be possible to have the VM Power State return as one of the values from the VM discovery.  We have a multi-tenant environment and in test cloud environment where there is a large number of VM which are powered off (hundred +) and I have noticed that Zabbix puts a lot of load on the vCenter server trying to retrieve data that is relevant.  What I would like to do is filter the discovery so it does not add any VMs that are not powered ON.

I have also noticed an issue with the below two Zabbix cluster check which always return a value of 0, which is incorrect;

cluster.cpu[name,usage] 
cluster.mem[name,free]

**Comment by dav3860** [comment] 2016-06-13 15:20
Hi,
Regarding the faulty methods, this will be fixed in the next release.

For the discovery, the problem is that event with caching, it would take some time to add the power state to the JSON array returned by VmBix (about 30-40% overhead). So a vm.discovery[full] method will be added in the next release, with the power state.

**Comment by dav3860** [comment] 2016-06-20 11:23
The methods have been fixed in the new release and a vm.discovery.full[*] method was added in VmBix 2.2. See README and CHANGELOG. You can download the packages [here](https://bintray.com/dav3860/generic/vmbix/view#files/2.2).

**Closed by dav3860** 2016-06-20 11:23 UTC
